version: "3"

services:
  test:
    container_name: judge-server
    build:
      context: .
      dockerfile: Dockerfile.develop
    volumes:
      - ./src:/app/src
    tty: true

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  judge-server:
    name: "judge-server-net"
